// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmaofgxmkwsdjlufrqrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtYW9mZ3hta3dzZGpsdWZycXJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NTM1MzQsImV4cCI6MjA2MDQyOTUzNH0.PNYMlXJSTOjHH5zjcbonbz7DVe90QKILsew9jT7Oy28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);